### ISSUE TITLE
You Tube problem

### ISSUE THREAD

**Issue by vengigat** [hjgwmvya/download-bar#3]
I think once already reported. The problem is as follows:

![screenshot_fri_mar_25_19 17 50](https://cloud.githubusercontent.com/assets/18075089/14050823/bdcdbfb2-f2be-11e5-97bd-fa0822f9963e.png)

![screenshot_fri_mar_25_19 18 07](https://cloud.githubusercontent.com/assets/18075089/14050829/c91c1ddc-f2be-11e5-970e-516e3135cb7a.png)

As shown in the accompanying shots while the download bar at the YouTube player decreases on both sides appear gray striped background.

**Comment by hjgwmvya** [comment]
Sorry, but i can't reproduce the problem. The player gets only smaller if i change the window width. Changes on the window (or inline) height have no effects.

**Comment by vengigat** [comment]
@hjgwmvya  I recorded a video where you can see how it looks at me this problem. The file format is MP4.

Download here:

https://my.pcloud.com/publink/show?code=XZPfO8ZqjAxwzssDuhpBcTkJopXB5aDtKG7

**Comment by hjgwmvya** [comment]
I can't reproduce this behavior. I have tested it with same url and with a clean profile on Fx 45. Which Fx version do you use? Can you try it with a clean Fx profile? Maybe an other add-on causes this problem.
