### ISSUE TITLE
Feature Request - Show filename instead of download URL & Hide downloads that open automatically

### ISSUE THREAD

**Issue by m890** [hjgwmvya/download-bar#5]
I can't code, but I really like your add on and it would be great to see these 2 features added.

The second feature I want added is because when I download torrent files I have it set to automatically open with my client, but the download bar always gets unnecessarily flooded with downloads.

If there's no way to detect if downloads open automatically then a good alternative would be to provide a custom filter for certain file types in a "Do not show in download bar" option.

Thanks!

**Comment by hjgwmvya** [comment]
Thanks for your suggestions.

In version 0.5 there are two new user settings:
 * Hide auto opening downloads
 * Download button text: Download URL or Local File Path

You have to enable this new options under add-on options if you want to use it. Downloads will be only ignored if they are open automatically and if there is no additional request for downloading.
